pipeline {
    agent none

    stages {
        stage('Compile') {
            agent { label 'slave-compile' }
            steps {
                sh 'mvn clean compile'
            }
        }

        stage('Test') {
            agent { label 'slave-test' }
            steps {
                sh 'mvn test'
            }
        }

        stage('Run Node container') {
            agent { label 'slave-test' } // Or any node with Docker installed
            steps {
                // Run Node inside Docker
                sh 'docker run --rm node:16-alpine node --version'
            }
        }
    }
}
